// module.exports="mongodb://127.0.0.1:27017"
//module.exports = "mongodb://localhost:28017"
module.exports="mongodb+srv://admin:admin@college.mxvuwtf.mongodb.net/?retryWrites=true&w=majority"
// module.exports="mongodb+srv://admin:admin@college.mxvuwtf.mongodb.net/?retryWrites=true&w=majority"
// module.exports="mongodb+srv://admin:college@college.mxvuwtf.mongodb.net/?retryWrites=true&w=majority"